version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

env:
  - VERSION={{ .Env.VERSION }}
  - COMMIT_HASH={{ .Env.COMMIT_HASH }}
  - BUILD_DATE={{ .Env.BUILD_DATE }}
  - BUILD_USER={{ .Env.BUILD_USER }}

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X slimserve/internal/version.Version=${VERSION}
      - -X slimserve/internal/version.CommitHash=${COMMIT_HASH}
      - -X slimserve/internal/version.BuildDate=${BUILD_DATE}
      - -X slimserve/internal/version.BuildUser=${BUILD_USER}
    main: ./cmd/slimserve/main.go

archives:
  - formats: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: saveside
    name: slimserve
  footer: |-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

checksum:
  disable: true
