apiVersion: v2
name: slimserve-helm
description: A lightweight HTTP file server designed with simplicity and security in mind.
type: application
version: 1.0.1
appVersion: 0.3.2
projectUrl: https://github.com/xeome/slimserve
maintainers:
- name: Emin
  email: xeome@proton.me
- name: Taha
  email: mt190502@mtaha.dev
- name: Yağız
  email: savew@savew.dev
