image:
  main:
    repository: ghcr.io/xeome/slimserve
    pullPolicy: IfNotPresent
    # tag: 0.3.1

main:
  ports:
    - containerPort: 8080
  auth:
    enabled: false
    name: loginusr1
    password: password1
    secret: 
      enabled: true
      autoCreate: true
      name: auth-password
      key: password
  dashboard:
    enabled: false
    autoCreate: true
    username: admin
    password: password2
    secret: 
      enabled: true
      autoCreate: true
      name: admin-credentials
      usernameKey: username
      passwordKey: password
  options:
    slimserve_dirs: "/data"
    slimserve_disable_dotfiles: "false"
    slimserve_log_level: "info"
    slimserve_enable_auth: "false"
  environments: {}
    # - name: key
    #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
