{{- if and .Values.main.auth.enabled (eq (.Values.main.auth.secret.enabled | toString) "true") (eq (.Values.main.auth.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.main.auth.secret.name }}{{ .Values.main.auth.secret.name }}{{ else }}{{ .Release.Name }}-auth-secret{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}slimserve{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.main.auth.secret.key }}: "{{ .Values.main.auth.password | b64enc }}"
{{- end }}

{{- if and .Values.main.dashboard.enabled (eq (.Values.main.dashboard.secret.enabled | toString) "true") (eq (.Values.main.dashboard.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.main.dashboard.secret.name }}{{ .Values.main.dashboard.secret.name }}{{ else }}{{ .Release.Name }}-dashboard-secret{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}slimserve{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.main.dashboard.secret.usernameKey }}: "{{ .Values.main.dashboard.username | b64enc }}"
  {{ .Values.main.dashboard.secret.passwordKey }}: "{{ .Values.main.dashboard.password | b64enc }}"
{{- end }}
