name: goreleaser

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  # packages: write
  # issues: write

env:
  VERSION: ${{ github.ref_name }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
          BUILD_USER: ${{ github.actor }}
          BUILD_DATE: ${{ github.run_started_at }}
