name: Release Helm Charts

on:
  push:
    paths:
      - 'manifests/helm/**'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release charts
        run: |
          helm package manifests/helm

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Helm Chart
        run: |
          helm push ${{ github.workspace }}/*.tgz oci://ghcr.io/${{ github.repository_owner }}/
